version: '3.8'

services:
  catalog-db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Ss123456"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - catalog-network

  redis:
    image: "redis:latest"
    container_name: "my-redis-container"
    ports:
      - "6379:6379"

  identity-service:
    container_name: lde.identityserver
    build:
      context: .
      dockerfile: IdentityServer/IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - MvcUrl=http://www.alevelwebsite.com
      - CatalogApi=http://www.alevelwebsite.com:6001
      - BasketApi=http://www.alevelwebsite.com:5003
    ports:
      - 5002:5002
    depends_on:
      - identity-db

  identity-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: identity-db
    environment:
      SA_PASSWORD: "Ss123456"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - catalog-network

networks:
  catalog-network:
    driver: bridge




