version: '3.8'

services:
  catalog-db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Ss123456"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - catalog-network

networks:
  catalog-network:
    driver: bridge
