version: '3.8'

services:
  catalog-db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Ss123456"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - catalog-network
  redis:
    image: "redis:latest"
    container_name: "my-redis-container"
    ports:
      - "6379:6379"

  identity-service:
    image: your-identity-service-image:latest
    container_name: identity-service
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - identity-db

  identity-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: identity-db
    environment:
      SA_PASSWORD: "Ss123456"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"

networks:
  catalog-network:
    driver: bridge



